### ISSUE TITLE
Feature: Add support for making files available in /home/hadoop without upload

### ISSUE THREAD

**Issue by amajedi** [jwplayer/sparksteps#27]
The only way currently to make additional files available in `/home/hadoop` on the master node is to use the `--uploads` feature. This is not ideal, since in certain situations, the files are already available in S3, therefore the upload step can be skipped.

**Comment by RikHeijdens** [comment]
One approach to support this while maintaining backwards compatibility is to alter the [`upload_steps()`](https://github.com/jwplayer/sparksteps/blob/master/sparksteps/steps.py#L158) function in order to support copying files to `/home/hadoop` without _actually_ uploading them to S3 first _if_ the provided `src_path` is a S3 URL. In this scenario you could simply supply s3 urls to the `--uploads` CLI parameter which will then be copied to `/home/hadoop` by the `CopyStep`.

**Comment by amajedi** [comment]
@RikHeijdens A reasonable approach, that's what I was thinking as well and how I decided to implement it in #28
